### ISSUE TITLE
Throwing an exception after installation

### ISSUE THREAD

**Issue by sbw92** [chapagain/auto-currency-switcher-2#1]
1 exception(s): Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by (output started at /home/username/public_html/magento/app/code/Chapagain/AutoCurrency/registration.php:9) in /home/username/public_html/magento/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 125 Exception #0 (Exception): Warning: Cannot modify header information - headers already sent by (output started at /home/username/public_html/magento/app/code/Chapagain/AutoCurrency/registration.php:9) in /home/username/public_html/magento/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php on line 125 #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Cannot modify h...', '/home/username/...', 125, Array) #1 /home/username/public_html/magento/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(125): setcookie('form_key', 'OBPrUzQ1TnPYumW...', 1482899227, '/admin_shaneb', 'www.invest-in-b...', false, false) #2 /home/username/public_html/magento/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php(98): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie('form_key', 'OBPrUzQ1TnPYumW...', Array) #3 /home/username/public_html/magento/vendor/magento/framework/App/PageCache/FormKey.php(74): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie('form_key', 'OBPrUzQ1TnPYumW...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata)) #4 /home/username/public_html/magento/vendor/magento/module-page-cache/Observer/RegisterFormKeyFromCookie.php(89): Magento\Framework\App\PageCache\FormKey->set('OBPrUzQ1TnPYumW...', Object(Magento\Framework\Stdlib\Cookie\PublicCookieMetadata)) #5 /home/username/public_html/magento/vendor/magento/module-page-cache/Observer/RegisterFormKeyFromCookie.php(69): Magento\PageCache\Observer\RegisterFormKeyFromCookie->updateCookieFormKey('OBPrUzQ1TnPYumW...') #6 /home/username/public_html/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\PageCache\Observer\RegisterFormKeyFromCookie->execute(Object(Magento\Framework\Event\Observer)) #7 /home/username/public_html/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\PageCache\Observer\RegisterFormKeyFromCookie), Object(Magento\Framework\Event\Observer)) #8 /home/username/public_html/magento/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #9 /home/username/public_html/magento/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array) #10 /home/username/public_html/magento/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array) #11 /home/username/public_html/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #12 /home/username/public_html/magento/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(59): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #13 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http)) #14 /home/username/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent('dispatch', Array) #15 /home/username/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Array, 'adminAuthentica...') #16 /home/username/public_html/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http)) #17 /home/username/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #18 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Array, 'adminMassaction...') #19 /home/username/public_html/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #20 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #21 /home/username/public_html/magento/var/generation/Magento/Config/Controller/Adminhtml/System/Config/Index/Interceptor.php(26): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins('dispatch', Array, Array) #22 /home/username/public_html/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #23 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #24 /home/username/public_html/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #25 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install') #26 /home/username/public_html/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #27 /home/username/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #28 /home/username/public_html/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #29 /home/username/public_html/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #30 /home/username/public_html/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch() #31 /home/username/public_html/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #32 {main}

**Comment by chapagain** [comment]
Just committed an update to the code https://github.com/chapagain/auto-currency-switcher-2/commit/e8d3ac8e46509344b4ce09233667995094cadb73 

Could you please check if this fixes the exception?

**Comment by sbw92** [comment]
Yes it worked! Thank you very much for this very useful extension!

**Comment by sbw92** [comment]
Just one more problem, I changed my IP to a uk IP and instead of changing to GBP it changed to USD, is there any settings that I could configure to fix it?
