### ISSUE TITLE
The default store only loading it does not load IP based country store.

### ISSUE THREAD

**Issue by pushparaj100** [chapagain/auto-currency-switcher-2#2]
Hi Chapagain,

I just installed and enabled the plugin.
its did not reload that country of store automatically. Anything i missed it run by default.
Please send me clear documentation for load store customer based ipaddress country of store.

Thanks advance,
Pushparaj

**Comment by chapagain** [comment]
Hi @pushparaj100 ,

This extension is intended to switch currency instead of switching store.

Thank you,
Mukesh

**Comment by pavan03kv** [comment]
HI ,
i have installed this extension,  but one categorie showing USD and other categorie showing INR, when am i browse the site from india IP 
Please guide me  to fix the issue

Thanks,
Pavan

**Comment by pradeepnew** [comment]
Hi @Pavanvaddi,
Same issue occur from my side also. Have you found any solution for this?

**Comment by chapagain** [comment]
This issue is fixed.

This was fixed in PR #5 and the PR is now merged to the master branch.

**Comment by chapagain** [comment]
This issue is fixed.

This was fixed in PR #5  and the PR is now merged to the master branch.
