### ISSUE TITLE
issue full page cache in Magento 2.3.4 

### ISSUE THREAD

**Issue by vtransy** [chapagain/auto-currency-switcher-2#3]
this module get cache issue when enable full page cache in Magento 2.3.4. the price currency not change when change ip and cache enabled.

**Comment by fawazrj** [comment]
did you solve the problem?
i disabled the cache but it didn't work with me
can you help me?

**Comment by chapagain** [comment]
Yes, this module has issue with full page cache turned on. I am trying to figure out to make it work with full page cache. 

It should work when full page cache is disabled.

**Comment by vtransy** [comment]
you can use this. I made this and using it now for my site
https://github.com/vtransy/magento2-geo-ip-store-currency-switcher

**Comment by fawazrj** [comment]
it didnt work when full page cache is disabled
can you enter to my device by Any desk and help me..
i need it alot for my work

**Comment by fawazrj** [comment]
did this code 
need more than one store?
i have only one store and  two currency

**Comment by vtransy** [comment]
@fawazrj would you need magento to developer?

**Comment by alexryall** [comment]
Just made a PR #5 which fixes the issue.

**Comment by chapagain** [comment]
This issue is fixed.

This was fixed in PR #5 and the PR is now merged to the master branch.
